apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
        - name: mongo-persistent-storage
          # Default storage path for mongo
          mountPath: /data/db
      volumes: 
      - name: mongo-persistent-storage
        # hostPath:
        #   path: /mnt/mongo-storage/
        #   type: DirectoryOrCreate
        persistentVolumeClaim:
          claimName: mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  # This defines which pods are going to be represented by this service
  # This service becomes the network endpoint for either other services or
  # external users to connect to (browsers)
  selector:
    app: mongodb

  ports:
    # name is just a label
    - name: mongoport
      port: 27017

  type: ClusterIP