apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # This defines which pods are going to be represented by this service
  # This service becomes the network endpoint for either other services or
  # external users to connect to (browsers)
  selector:
    app: queue

  ports:
    # name is just a label
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  type: NodePort