apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this service
  # This service becomes the network endpoint for either other services or
  # external users to connect to (browsers)
  selector:
    app: webapp

  ports:
    # name is just a label
    - name: http
      port: 80
      # targetPort is not necessarily required. If not specified, targetPort will be assigned same as port
      targetPort: 80
      nodePort: 30081

  type: NodePort